export const SET_USER = 'SET_USER';
export const REQUESTING_DATA = 'REQUESTING_DATA';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
export const REQUESTING_EXERCISES = 'REQUESTING_EXERCISES';
export const RECEIVING_EXERCISES = 'RECEIVING_EXERCISES';
